Numpy Ve liste farkları

In [2]:
#liste kullanımı hata verir
a=[1,5,10]
b=[1,2,3]
c=a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [4]:
import numpy as np
a = np.array([1,5,10]) 
    
b = np.array([1,2,3])

c=a*b
c

array([ 1, 10, 30])

In [ ]:
a = np.array([1,5,10])
print(a)

[ 1  5 10]


In [ ]:
b = np.array([[1,7,20], [5, 8, 9]])
print(b)

[[ 1  7 20]
 [ 5  8  9]]


In [ ]:
#dizi boyutu öğrenme
b.ndim

2

In [ ]:
#bout öğrenme
b.shape

(2, 3)

In [ ]:
b.dtype

dtype('int32')

In [ ]:
x = np.array([1.0,5.4,10.42])
x.dtype

dtype('float64')

In [ ]:
print(b)

[[ 1  7 20]
 [ 5  8  9]]


In [ ]:
b[0,2]

20

In [ ]:
b[1,1]

8

In [ ]:
b[0]

array([ 1,  7, 20])

In [ ]:
#ilk satırdaki ikinci ve ücüncü elemanlara - yani 7 ve 20'ye erişmek için : kullanırız
b[0,1:]

array([ 7, 20])

In [ ]:
b[1, 1] = 18
b[1, 1]

18

In [ ]:
b

array([[ 1,  7, 20],
       [ 5, 18,  9]])

Otomatik dizi oluşturma

In [ ]:
dizi_s = np.zeros((2,3))
dizi_s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
dizi1= np.full((4,4), 50)
dizi1

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])

In [ ]:
# Random dizi oluşturma
dizi2 = np.random.rand(4,3)
dizi2

array([[0.24232075, 0.93639704, 0.56075529],
       [0.3587714 , 0.11077602, 0.3488945 ],
       [0.39297045, 0.43927598, 0.26496607],
       [0.27907663, 0.86837404, 0.32831342]])

In [ ]:
dizi3 = np.random.randint(0,100,size=(5,5))
dizi3

array([[67,  1, 62, 88,  7],
       [64, 68, 52, 39, 82],
       [41, 63, 64, 15, 14],
       [61, 41, 73, 74,  0],
       [19, 68, 34, 90, 16]])

In [ ]:
#dizi kopyalarken dikkat!!!
a = np.array([1,2,3])
b = a
b[0] = 90

print(a)

[90  2  3]


In [ ]:
# b bir pointer gibi a'nın gösterdiği aynı memory lokoasyonunu gösteriyor o nedenle b deki değişiklik a da da oluyor.
# bu tarz durumlarla karşılaşmamak için copy() fonksyionunu kullanın:
a = np.array([1,2,3])
b = a.copy()
b[0] = 90

print(a)

[1 2 3]


In [ ]:
print(b)

[90  2  3]


Matematiksel işlemler

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a+4

array([5, 6, 7, 8])

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [ ]:
a**2

array([ 1,  4,  9, 16])

İstatistik

In [ ]:
dizi4 = np.random.randint(0,100,size=49)
dizi4

array([11, 59, 22, 79, 64, 28, 87, 89, 67,  1, 69, 16, 32, 17, 54, 96, 88,
       38, 75, 38, 69,  9,  1, 24, 65, 33, 42, 34, 84, 39,  0, 76, 34, 23,
       28, 12, 80, 71, 58, 51, 80, 45, 25, 39, 41, 16, 29,  9, 38])

In [ ]:
np.min(dizi4)

0

In [ ]:
np.max(dizi4)

96

In [ ]:

np.sum(dizi4)

21

In [5]:
dosya = np.genfromtxt('ornek.txt', delimiter=',')
dosya = dosya.astype('int32')
print(dosya)

[[1 2 3 4 5 6 7]
 [8 9 7 8 9 9 8]
 [3 3 3 5 7 9 0]]


In [7]:
dosya[1,0]

8